server:
  port: 8084

spring:
  application:
    name: assessment-service

patient-service:
  base-url: ${PATIENT_SERVICE_URL:http://localhost:8081}

notes-service:
  base-url: ${NOTES_SERVICE_URL:http://localhost:8083}