server:
  port: 8082

spring:
  application:
    name: front-service

gateway:
  base-url: ${GATEWAY_BASE_URL:http://localhost:8080}

assessment-service:
  base-url: ${ASSESSMENT_SERVICE_BASE_URL:http://localhost:8084}