name: Medilabo CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - test
  pull_request:
    branches:
      - main
      - test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupération du code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Java
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      # 3. Build & tests (tous les services)
      - name: Build & run tests
        run: mvn clean verify

      # 4. Packaging
      - name: Package application
        run: mvn clean package -DskipTests

      # 5. Upload des artefacts (jar)
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: medilabo-jars
          path: |
            patient-service/target/*.jar
            notes-service/target/*.jar
            assessment-service/target/*.jar
            gateway-service/target/*.jar
            front-service/target/*.jar